# Generated by Django 5.1.1 on 2025-01-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/pics/'),
        ),
        migrations.AddField(
            model_name='officeadmin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='office/pics/'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/pics/'),
        ),
    ]
