# Generated by Django 5.1.1 on 2025-02-05 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_faculty_faculty_id'),
        ('features', '0002_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.faculty', to_field='faculty_id'),
        ),
    ]
