# Generated by Django 5.1.1 on 2024-10-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='facultydb',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='backend.section'),
        ),
        migrations.AlterField(
            model_name='facultydb',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Principal', 'Principal'), ('Coordinator', 'Coordinator'), ('Admin', 'Admin')], max_length=50),
        ),
        migrations.AddField(
            model_name='facultydb',
            name='subjects',
            field=models.ManyToManyField(related_name='faculty', to='backend.subject'),
        ),
    ]
